collection_name: Faces

id_field:
  name: id
  dtype: INT64                # 数据类型：整型
  description: face_ids
  is_primary: true            # 是否为主键字段

name_field:
  name: name
  dtype: VARCHAR              # 数据类型：可变字符
  description: names of faces
  max_length: 50              # 最大长度限制
embedding_field:
  name: normed_embedding
  dtype: FLOAT_VECTOR         # 数据类型：浮点向量
  description: face_normed_embedding vector
  dim: 512                    # 向量维度
# 索引和搜索参数
index_file_size: 32           # 索引文件的最大大小（MB）
shards_num: 6                 # 集合分片的数量->需要测试得到最佳值
index_type: IVF_FLAT          # 索引类型
metric_type: IP               # 度量类型：内积
nlist: 1024                   # 聚类的数量（索引参数）->需要测试得到最佳值
nprobe: 20                    # 搜索时的聚类数量（搜索参数）->需要测试得到最佳值
top_k: 1                      # 返回的最大结果数
